# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kind2anki_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kind2ankiDialog(object):
    def setupUi(self, kind2ankiDialog):
        kind2ankiDialog.setObjectName("kind2ankiDialog")
        kind2ankiDialog.resize(376, 199)
        self.vboxlayout = QtWidgets.QVBoxLayout(kind2ankiDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.group_box_content = QtWidgets.QGroupBox(kind2ankiDialog)
        self.group_box_content.setObjectName("group_box_content")
        self.top_layout = QtWidgets.QVBoxLayout(self.group_box_content)
        self.top_layout.setObjectName("top_layout")
        self.grid_layout_model_deck = QtWidgets.QGridLayout()
        self.grid_layout_model_deck.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.grid_layout_model_deck.setObjectName("grid_layout_model_deck")
        self.model_area = QtWidgets.QWidget(self.group_box_content)
        self.model_area.setObjectName("model_area")
        self.grid_layout_model_deck.addWidget(self.model_area, 0, 1, 1, 1)
        self.label_model = QtWidgets.QLabel(self.group_box_content)
        self.label_model.setObjectName("label_model")
        self.grid_layout_model_deck.addWidget(self.label_model, 0, 0, 1, 1)
        self.deck_area = QtWidgets.QWidget(self.group_box_content)
        self.deck_area.setObjectName("deck_area")
        self.grid_layout_model_deck.addWidget(self.deck_area, 1, 1, 1, 1)
        self.label_deck = QtWidgets.QLabel(self.group_box_content)
        self.label_deck.setObjectName("label_deck")
        self.grid_layout_model_deck.addWidget(self.label_deck, 1, 0, 1, 1)
        self.top_layout.addLayout(self.grid_layout_model_deck)
        self.import_mode = QtWidgets.QComboBox(self.group_box_content)
        self.import_mode.setObjectName("import_mode")
        self.import_mode.addItem("")
        self.import_mode.addItem("")
        self.import_mode.addItem("")
        self.top_layout.addWidget(self.import_mode)
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setObjectName("grid_layout")
        self.label = QtWidgets.QLabel(self.group_box_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.grid_layout.addWidget(self.label, 1, 0, 1, 1)
        self.include_usage = QtWidgets.QCheckBox(self.group_box_content)
        self.include_usage.setChecked(True)
        self.include_usage.setObjectName("include_usage")
        self.grid_layout.addWidget(self.include_usage, 0, 0, 1, 1)
        self.label_import_days = QtWidgets.QLabel(self.group_box_content)
        self.label_import_days.setMinimumSize(QtCore.QSize(169, 0))
        self.label_import_days.setObjectName("label_import_days")
        self.grid_layout.addWidget(self.label_import_days, 2, 0, 1, 1)
        self.import_days = QtWidgets.QSpinBox(self.group_box_content)
        self.import_days.setMinimum(1)
        self.import_days.setMaximum(1000)
        self.import_days.setProperty("value", 10)
        self.import_days.setObjectName("import_days")
        self.grid_layout.addWidget(self.import_days, 2, 1, 1, 1)
        self.label_days = QtWidgets.QLabel(self.group_box_content)
        self.label_days.setObjectName("label_days")
        self.grid_layout.addWidget(self.label_days, 2, 2, 1, 1)
        self.language_select = QtWidgets.QComboBox(self.group_box_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language_select.sizePolicy().hasHeightForWidth())
        self.language_select.setSizePolicy(sizePolicy)
        self.language_select.setToolTipDuration(-6)
        self.language_select.setEditable(True)
        self.language_select.setObjectName("language_select")
        self.language_select.addItem("")
        self.language_select.addItem("")
        self.language_select.addItem("")
        self.language_select.addItem("")
        self.language_select.addItem("")
        self.language_select.addItem("")
        self.grid_layout.addWidget(self.language_select, 1, 1, 1, 2)
        self.do_translate = QtWidgets.QCheckBox(self.group_box_content)
        self.do_translate.setChecked(True)
        self.do_translate.setObjectName("do_translate")
        self.grid_layout.addWidget(self.do_translate, 0, 1, 1, 2)
        self.top_layout.addLayout(self.grid_layout)
        self.vboxlayout.addWidget(self.group_box_content)
        self.button_box_standard_buttons = QtWidgets.QDialogButtonBox(kind2ankiDialog)
        self.button_box_standard_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.button_box_standard_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.button_box_standard_buttons.setObjectName("button_box_standard_buttons")
        self.vboxlayout.addWidget(self.button_box_standard_buttons)

        self.retranslateUi(kind2ankiDialog)
        self.language_select.setCurrentIndex(0)
        self.button_box_standard_buttons.accepted.connect(kind2ankiDialog.accept)
        self.button_box_standard_buttons.rejected.connect(kind2ankiDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(kind2ankiDialog)

    def retranslateUi(self, kind2ankiDialog):
        _translate = QtCore.QCoreApplication.translate
        kind2ankiDialog.setWindowTitle(_translate("kind2ankiDialog", "Import"))
        self.group_box_content.setTitle(_translate("kind2ankiDialog", "Kind2anki options"))
        self.label_model.setText(_translate("kind2ankiDialog", "Card"))
        self.label_deck.setText(_translate("kind2ankiDialog", "Deck"))
        self.import_mode.setItemText(0, _translate("kind2ankiDialog", "Update existing notes when first field matches"))
        self.import_mode.setItemText(1, _translate("kind2ankiDialog", "Ignore lines where first field matches existing note"))
        self.import_mode.setItemText(2, _translate("kind2ankiDialog", "Import even if existing note has same first field"))
        self.label.setText(_translate("kind2ankiDialog", "Language"))
        self.include_usage.setText(_translate("kind2ankiDialog", "Include usage example"))
        self.label_import_days.setText(_translate("kind2ankiDialog", "Import words not older than"))
        self.label_days.setText(_translate("kind2ankiDialog", "days"))
        self.language_select.setItemText(0, _translate("kind2ankiDialog", "ru"))
        self.language_select.setItemText(1, _translate("kind2ankiDialog", "de"))
        self.language_select.setItemText(2, _translate("kind2ankiDialog", "lt"))
        self.language_select.setItemText(3, _translate("kind2ankiDialog", "pt"))
        self.language_select.setItemText(4, _translate("kind2ankiDialog", "en"))
        self.language_select.setItemText(5, _translate("kind2ankiDialog", "es"))
        self.do_translate.setText(_translate("kind2ankiDialog", "Translate words"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kind2ankiDialog = QtWidgets.QDialog()
    ui = Ui_kind2ankiDialog()
    ui.setupUi(kind2ankiDialog)
    kind2ankiDialog.show()
    sys.exit(app.exec_())
